name = "fingerprint-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Exemplo de configuração de D1
# [[d1_databases]]
# binding = "DB"
# database_name = "seu_database"
# database_id = "seu_database_id" # Substitua pelo seu ID real